name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8 
      #This build will fail once one issue 
      #is found by the code sniffer
      #as we applied an aggresive config:
    - name: Detekt sniffing with Gradle
      run: ./gradlew build
